variables:
  IMAGE_NAME: registry.gitlab.com/$CI_PROJECT_PATH
  IMAGE_TAG: dev-v1.0
  STAGE_CONTAINER: dev
  PROD_CONTAINER: prod
  DEV_FOLDER: /home/ubuntu/swavey/dev
  PROD_FOLDER: /home/ubuntu/swavey/prod

stages:
  - test
  - build
  - stage
  - deploy

run_tests:
  stage: test
  image: node:16.15.1
  services:
    - mongo:latest
  before_script:
    - apt-get update && npm install
  script:
    # - mongodb -v
    - npm run test

build_dev:
  stage: build
  only:
    - dev
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login --username gitlab-ci-token --password $CI_BUILD_TOKEN registry.gitlab.com
  script:
    - docker build --tag $IMAGE_NAME/$STAGE_CONTAINER:$CI_COMMIT_SHA --tag $IMAGE_NAME/$STAGE_CONTAINER:latest .
    - docker push $IMAGE_NAME/$STAGE_CONTAINER:$CI_COMMIT_SHA
    - docker push $IMAGE_NAME/$STAGE_CONTAINER:latest
  after_script:
    - docker logout registry.gitlab.com

build_master:
  stage: build
  only:
    - master
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login --username gitlab-ci-token --password $CI_BUILD_TOKEN registry.gitlab.com
  script:
    - docker build --tag $IMAGE_NAME/$PROD_CONTAINER:$CI_COMMIT_SHA --tag $IMAGE_NAME/$PROD_CONTAINER:latest .
    - docker push $IMAGE_NAME/$PROD_CONTAINER:$CI_COMMIT_SHA
    - docker push $IMAGE_NAME/$PROD_CONTAINER:latest
  after_script:
    - docker logout registry.gitlab.com

stage:
  only:
    - dev
  stage: stage
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - scp -o StrictHostKeyChecking=no -i $SSH_KEY docker-compose.yml ubuntu@168.138.47.33:$DEV_FOLDER/docker-compose.yml
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY ubuntu@168.138.47.33 "
        docker login --username gitlab-ci-token --password $CI_BUILD_TOKEN registry.gitlab.com && 
        cd $DEV_FOLDER && 
        docker-compose pull $STAGE_CONTAINER && 
        sudo service $STAGE_CONTAINER restart && 
        docker logout registry.gitlab.com"

deploy:
  only:
    - master
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - scp -o StrictHostKeyChecking=no -i $SSH_KEY docker-compose.yml ubuntu@168.138.47.33:$PROD_FOLDER/docker-compose.yml
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY ubuntu@168.138.47.33 "
        docker login --username gitlab-ci-token --password $CI_BUILD_TOKEN registry.gitlab.com && 
        cd $PROD_FOLDER &&
        docker-compose pull $PROD_CONTAINER && 
        sudo service $PROD_CONTAINER restart && 
        docker logout registry.gitlab.com"

