# A workflow template for Angular project

name: CI

# the placeholder `$default-branch` will be automatically replaced with
# the name of the repository's default branch, e.g. main
on:
  [push]

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10.x]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run start

      - name: Test
        run: npm test